"use client";

import React from "react";
import { useTheme } from "@/hooks/useTheme";
import { DESIGN_TOKENS } from "@/constants/design";
import { MOCK_INTELLIGENCE_REPORTS } from "../constants/reportsData";
import { 
  ArrowLeft, BrainCircuit, FileBarChart, AlertTriangle, 
  TrendingUp, CheckCircle2, Server, Clock, GitCommit, FileText, Download, Target, Activity, ShieldAlert
} from "lucide-react";
import { useRouter } from "next/navigation";

interface ReportDetailWorkspaceProps {
  reportId: string;
  onBack: () => void;
}

export function ReportDetailWorkspace({ reportId, onBack }: ReportDetailWorkspaceProps) {
  const { theme } = useTheme();
  const tokens = DESIGN_TOKENS[theme];
  const router = useRouter();

  const report = MOCK_INTELLIGENCE_REPORTS.find(r => r.id === reportId);
  if (!report) return null;

  return (
    <div className="flex flex-col w-full pb-12">
      {/* Header Navigation */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <button 
            onClick={onBack}
            className="p-2 -ml-2 rounded-lg hover:bg-slate-800/50 transition-colors text-slate-400 hover:text-white"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <span className={`text-sm font-medium ${tokens.text.secondary}`}>Back to Executive Reports</span>
        </div>
        <button className={`px-4 py-2 rounded-xl bg-slate-800 border ${tokens.card.border} text-sm font-medium text-white hover:bg-slate-700 transition-colors flex items-center gap-2`}>
          <Download className="w-4 h-4 text-slate-400" />
          Export PDF
        </button>
      </div>

      {/* Hero Banner */}
      <div className={`flex flex-col md:flex-row md:items-center justify-between gap-6 p-6 rounded-2xl bg-slate-900/60 border ${tokens.card.border} mb-6 relative overflow-hidden`}>
        <div className="absolute top-0 right-0 w-64 h-64 bg-pink-500/10 rounded-full blur-3xl" />
        
        <div className="flex items-center gap-5 relative z-10">
          <div className={`w-16 h-16 rounded-2xl flex items-center justify-center border bg-pink-500/10 border-pink-500/20 text-pink-500`}>
            <FileBarChart className="w-8 h-8" />
          </div>
          <div>
            <div className="flex flex-wrap items-center gap-3 mb-2">
              <span className={`px-2 py-0.5 text-[10px] font-bold uppercase rounded bg-slate-800 ${tokens.text.primary}`}>
                {report.category}
              </span>
              <span className={`px-2 py-0.5 text-[10px] font-bold uppercase rounded bg-slate-800 ${tokens.text.primary}`}>
                {report.timeRange}
              </span>
              <span className={`px-2 py-0.5 text-[10px] font-bold uppercase rounded border border-emerald-500/20 bg-emerald-500/10 text-emerald-400`}>
                {report.status}
              </span>
            </div>
            <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">{report.title}</h1>
            <p className={`text-[12px] font-medium text-slate-400 mt-1`}>Generated by {report.generatedBy} &bull; {new Date(report.generatedAt).toLocaleString()}</p>
          </div>
        </div>
      </div>

      {/* Main Intelligence Body */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        
        {/* Left Column - The Executive Narrative */}
        <div className="xl:col-span-2 flex flex-col gap-6">
          
          {/* Section 1: Executive Narrative */}
          <div className={`p-6 rounded-2xl bg-gradient-to-br from-pink-950/30 to-slate-900/60 border border-pink-500/20 relative overflow-hidden`}>
            <div className="absolute top-0 left-0 w-1 h-full bg-pink-500/50" />
            <h2 className="text-sm font-bold text-pink-400 mb-6 flex items-center gap-2">
              <BrainCircuit className="w-5 h-5" />
              Executive Narrative
            </h2>
            
            <div className="space-y-6">
              <div>
                <h3 className={`text-[11px] uppercase font-bold text-slate-400 mb-2`}>What Happened</h3>
                <p className={`text-[14px] text-slate-200 leading-relaxed`}>{report.narrative.whatHappened}</p>
              </div>
              <div>
                <h3 className={`text-[11px] uppercase font-bold text-slate-400 mb-2`}>Why It Happened</h3>
                <p className={`text-[14px] text-slate-200 leading-relaxed`}>{report.narrative.whyItHappened}</p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h3 className={`text-[11px] uppercase font-bold text-amber-500 mb-2`}>Operational Impact</h3>
                  <p className={`text-[13px] ${tokens.text.secondary} leading-relaxed`}>{report.narrative.operationalImpact}</p>
                </div>
                <div>
                  <h3 className={`text-[11px] uppercase font-bold text-red-400 mb-2`}>Cost of Inaction</h3>
                  <p className={`text-[13px] ${tokens.text.secondary} leading-relaxed`}>{report.narrative.costOfInaction}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Section 2: Key Findings */}
          <div className={`p-6 rounded-2xl bg-slate-900/40 border ${tokens.card.border}`}>
            <h2 className="text-sm font-bold text-white mb-6 flex items-center gap-2">
              <Target className="w-5 h-5 text-blue-500" />
              Key Findings
            </h2>
            <div className="space-y-4">
              {report.findings.map(finding => (
                <div key={finding.id} className="p-4 bg-slate-950/50 rounded-xl border border-slate-800/50 flex flex-col gap-2">
                  <div className="flex items-center justify-between">
                    <h3 className="text-[14px] font-bold text-white">{finding.title}</h3>
                    <div className="flex items-center gap-2">
                      <span className={`text-[10px] font-bold uppercase px-1.5 py-0.5 rounded ${
                        finding.severity === 'Critical' ? 'bg-red-500/10 text-red-500' :
                        finding.severity === 'High' ? 'bg-orange-500/10 text-orange-500' : 'bg-amber-500/10 text-amber-500'
                      }`}>{finding.severity}</span>
                      <span className={`text-[10px] font-bold uppercase px-1.5 py-0.5 rounded border border-slate-700 bg-slate-800 text-slate-300`}>
                        {finding.trend}
                      </span>
                    </div>
                  </div>
                  <p className={`text-[13px] ${tokens.text.secondary} leading-relaxed`}>{finding.description}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Section 3: Data-Driven Charts */}
          <div className={`p-6 rounded-2xl bg-slate-900/40 border ${tokens.card.border}`}>
            <h2 className="text-sm font-bold text-white mb-6 flex items-center gap-2">
              <Activity className="w-5 h-5 text-emerald-500" />
              Operational Analytics
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {report.charts.map(chart => (
                <div key={chart.id} className="flex flex-col p-4 bg-slate-950/50 rounded-xl border border-slate-800/50">
                  <h3 className={`text-[11px] uppercase font-bold text-slate-400 mb-4`}>{chart.title}</h3>
                  
                  {/* Dynamic CSS Bar Chart Renderer */}
                  {chart.type === 'bar' && (
                    <div className="flex items-end justify-between h-32 gap-1 px-2 mt-auto">
                      {chart.labels.map((label, i) => {
                        // Assuming 2 series for this mock
                        const val1 = chart.series[0].data[i];
                        const val2 = chart.series[1].data[i];
                        const max = Math.max(...chart.series[0].data, ...chart.series[1].data);
                        return (
                          <div key={i} className="flex flex-col items-center justify-end h-full gap-1 w-full group relative">
                            <div className="flex gap-0.5 items-end justify-center w-full h-[calc(100%-20px)]">
                              <div className="w-full max-w-[12px] rounded-t-sm transition-all" style={{ height: `${(val1 / max) * 100}%`, backgroundColor: chart.series[0].color }} />
                              <div className="w-full max-w-[12px] rounded-t-sm transition-all" style={{ height: `${(val2 / max) * 100}%`, backgroundColor: chart.series[1].color }} />
                            </div>
                            <span className="text-[9px] text-slate-500 font-medium">{label}</span>
                          </div>
                        )
                      })}
                    </div>
                  )}

                  {/* Dynamic CSS Trend (Line) Renderer - Simplified using a step gradient/points for pure CSS */}
                  {chart.type === 'trend' && (
                    <div className="flex items-end justify-between h-32 gap-0 mt-auto relative px-4">
                      {chart.labels.map((label, i) => {
                        const val = chart.series[0].data[i];
                        return (
                          <div key={i} className="flex flex-col items-center justify-end h-full relative z-10">
                            <div className="w-2 h-2 rounded-full absolute -ml-1 transition-all shadow-[0_0_10px_rgba(16,185,129,0.5)]" style={{ bottom: `calc(${(val / 100) * 100}% + 20px)`, backgroundColor: chart.series[0].color }} />
                            <span className="text-[9px] text-slate-500 font-medium absolute bottom-0">{label}</span>
                          </div>
                        )
                      })}
                    </div>
                  )}
                  
                  {/* Chart Legend */}
                  <div className="flex items-center gap-4 mt-4 pt-4 border-t border-slate-800/50">
                    {chart.series.map(s => (
                      <div key={s.name} className="flex items-center gap-1.5">
                        <div className="w-2 h-2 rounded-full" style={{ backgroundColor: s.color }} />
                        <span className="text-[10px] text-slate-400">{s.name}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 5: Executive Decision Panel */}
          <div className={`p-6 rounded-2xl bg-gradient-to-br from-orange-950/30 to-slate-900/60 border border-orange-500/20`}>
            <h2 className="text-sm font-bold text-orange-400 mb-6 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5" />
              Executive Decision Panel
            </h2>
            
            <div className="space-y-6">
              <DecisionGroup title="Immediate Actions (24h)" actions={report.decisionPanel.immediateActions} color="text-red-400" />
              <DecisionGroup title="Short-Term Actions (7 Days)" actions={report.decisionPanel.shortTermActions} color="text-orange-400" />
              <DecisionGroup title="Long-Term Strategy" actions={report.decisionPanel.longTermImprovements} color="text-emerald-400" />
            </div>
          </div>

        </div>

        {/* Right Column - Evidence & Metadata */}
        <div className="space-y-6">

          {/* Section 4: AI Confidence */}
          <div className={`p-5 rounded-2xl bg-slate-900/40 border ${tokens.card.border}`}>
            <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" />
              Intelligence Confidence
            </h2>
            <div className="space-y-3">
              <ConfidenceRow label="Overall AI Confidence" val={report.confidence.aiConfidence} color="text-emerald-400" />
              <ConfidenceRow label="Evidence Trust" val={report.confidence.evidenceConfidence} color="text-emerald-400" />
              <ConfidenceRow label="Reasoning Engine" val={report.confidence.reasoningConfidence} color="text-emerald-400" />
              <ConfidenceRow label="Knowledge Coverage" val={report.confidence.knowledgeCoverage} color="text-emerald-400" />
              <ConfidenceRow label="Data Freshness" val={report.confidence.dataFreshness} color="text-emerald-400" />
            </div>
          </div>

          {/* Section 6: Affected Assets */}
          <div className={`p-5 rounded-2xl bg-slate-900/40 border ${tokens.card.border}`}>
            <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <Server className="w-4 h-4 text-blue-500" />
              Impacted Assets
            </h2>
            <div className="space-y-2">
              {report.affectedAssets.map(asset => (
                <div key={asset.id} onClick={() => router.push("/demo/assets")} className="flex items-center justify-between p-3 bg-slate-950/50 rounded-xl hover:bg-slate-800/80 border border-slate-800/50 transition-colors cursor-pointer group">
                  <div className="flex items-center gap-3">
                    <div className="p-1.5 rounded-md bg-blue-500/10 text-blue-400">
                      <Server className="w-4 h-4" />
                    </div>
                    <div className="flex flex-col">
                      <span className="text-[13px] font-bold text-slate-200 group-hover:text-blue-400 transition-colors">{asset.tag}</span>
                      <span className={`text-[11px] ${tokens.text.secondary}`}>{asset.name}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 7: Knowledge Insights */}
          <div className={`p-5 rounded-2xl bg-slate-900/40 border ${tokens.card.border}`}>
            <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <BrainCircuit className="w-4 h-4 text-purple-500" />
              Graph Insights
            </h2>
            <div className="space-y-3">
              {report.knowledgeInsights.map((insight, i) => (
                <div key={i} className="p-3 bg-purple-500/5 border border-purple-500/20 rounded-xl">
                  <p className="text-[12px] font-medium text-purple-100/80 leading-relaxed">
                    <strong className="text-purple-400 block mb-1">{insight.split(':')[0]}:</strong>
                    {insight.split(':')[1]}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Section 3: Traceable Evidence Center */}
          <div className={`p-5 rounded-2xl bg-slate-900/40 border ${tokens.card.border}`}>
            <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <FileText className="w-4 h-4 text-pink-500" />
              Traceable Evidence
            </h2>
            <div className="space-y-2">
              {report.evidence.map(ev => (
                <div key={ev.id} className="flex items-center justify-between p-3 bg-slate-950/50 rounded-xl border border-slate-800/50 hover:bg-slate-800/80 transition-colors cursor-pointer group">
                  <div className="flex flex-col">
                    <span className="text-[12px] font-bold text-slate-200 group-hover:text-pink-400 transition-colors line-clamp-1">{ev.title}</span>
                    <span className={`text-[10px] font-medium ${tokens.text.secondary}`}>{ev.type}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 8: Report History */}
          <div className={`p-5 rounded-2xl bg-slate-900/40 border ${tokens.card.border}`}>
            <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <GitCommit className="w-4 h-4 text-slate-400" />
              Report History
            </h2>
            <div className="relative border-l border-slate-700/50 ml-2 space-y-4 pb-1">
              {report.history.map((ver, idx) => (
                <div key={idx} className="relative pl-4">
                  <div className={`absolute -left-[5px] top-1.5 w-2.5 h-2.5 rounded-full ring-4 ring-slate-900 ${idx === 0 ? 'bg-emerald-500' : 'bg-slate-600'}`} />
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-[11px] font-bold text-white">{ver.version}</span>
                    <span className="text-[9px] text-slate-400">{new Date(ver.generatedDate).toLocaleTimeString()}</span>
                  </div>
                  <p className={`text-[11px] ${tokens.text.secondary}`}>{ver.changesSinceLast}</p>
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}

function ConfidenceRow({ label, val, color }: { label: string, val: number, color: string }) {
  return (
    <div className="flex items-center justify-between p-2 rounded-lg bg-slate-950/50 border border-slate-800/50">
      <span className={`text-[11px] font-bold text-slate-300`}>{label}</span>
      <span className={`text-[12px] font-bold ${val > 90 ? color : 'text-amber-500'}`}>{val}%</span>
    </div>
  )
}

function DecisionGroup({ title, actions, color }: { title: string, actions: any[], color: string }) {
  if (actions.length === 0) return null;
  return (
    <div>
      <h3 className={`text-[11px] uppercase font-bold ${color} mb-3 flex items-center gap-1.5`}>
        {title}
      </h3>
      <div className="space-y-3">
        {actions.map((act, i) => (
          <div key={i} className="p-4 bg-slate-950/50 rounded-xl border border-slate-800/50 hover:border-orange-500/30 transition-colors cursor-pointer group">
            <div className="flex items-center justify-between mb-2">
              <span className={`text-[10px] font-bold uppercase px-1.5 py-0.5 rounded bg-slate-800 text-slate-300`}>
                Dept: {act.department}
              </span>
            </div>
            <span className="block text-[13px] font-bold text-white mb-1 group-hover:text-orange-400 transition-colors">{act.action}</span>
            <p className={`text-[11px] ${DESIGN_TOKENS.dark.text.secondary}`}>{act.impact}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
